5final/board_without_scaffold/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :my_threads do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  root 'my_threads#index'

end

5final/board_without_scaffold/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

5final/board_without_scaffold/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :my_thread
  belongs_to :user
end

5final/board_without_scaffold/app/models/my_thread.rb
class MyThread < ApplicationRecord
  has_many :comments
  belongs_to :user
end

5final/board_without_scaffold/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :my_threads
end

5final/board_without_scaffold/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

5final/board_without_scaffold/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_my_thread
  before_action :set_comment, only: %i[ edit update destroy ]

  def create
    #@my_thread.comments.create(comment_params)
    @comment = current_user.comments.build(body: comment_params[:body], my_thread: @my_thread)
    @comment.save
    # redirect_to my_thread_path(@my_thread) = my_thread_path(@my_thread.id)
    redirect_to @my_thread, notice: '新しいコメントが作成されました'
  end

  def edit
    user_check
  end

  def update
    if current_user.id == @comment.user_id
      if @comment.update(comment_params)
        redirect_to @my_thread, notice: 'コメントが正しく変更されました'
      else
        render 'edit'
      end
    else
      redirect_to @my_thread and return
    end

  end

  def destroy
    if current_user.id == @comment.user_id
      @comment.destroy
      redirect_to @my_thread, notice: 'コメントが削除されました'
    else
      redirect_to @my_thread and return
    end
  end


  private

    def set_my_thread
      @my_thread = MyThread.find(params[:my_thread_id])
    end

    def set_comment
      # @comment = @my_thread.comments.find(params[:id])
      @comment = Comment.find(params[:id])
    end


    def comment_params
      params.require(:comment).permit(:body)
    end

    def user_check
      if current_user.id == @comment.user_id
        return true
      else
        redirect_to @my_thread
      end
    end


end

5final/board_without_scaffold/app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
  before_action :set_my_thread, only: %i[ show edit update destroy ]

  def index
    @my_threads = MyThread.all
  end

  def show

  end

  def new
    @my_thread = MyThread.new
  end

  def create
    #@my_thread = MyThread.create(my_thread_params)
    #@my_thread = MyThread.new(my_thread_params)
    @my_thread = current_user.my_threads.build(my_thread_params)
    if @my_thread.save
      # flash[:notice] = "新規スレッドが作成されました"
      # redirect_to my_threads_path
      redirect_to my_threads_path, notice: "新規スレッドが作成されました"
    else
      flash.now[:alert] = "失敗しました"
      render :new #new.html.erbに飛んでくれる
    end

  end

  def edit
    user_check
  end

  def update
    if current_user.id == @my_thread.user_id
      if @my_thread.update(my_thread_params)
        redirect_to my_threads_path, notice: 'スレッドが正しく変更されました'
      else
        render 'edit'
      end
    else
      redirect_to my_threads_path and return
    end
  end

  def destroy
    if current_user.id == @my_thread.user_id
      @my_thread.destroy
      redirect_to my_threads_path, notice: 'スレッドが削除されました'
    else
      redirect_to my_threads_path and return
    end
  end



  private
    def set_my_thread
      @my_thread = MyThread.find(params[:id])
    end

    def my_thread_params
      params.require(:my_thread).permit(:title)
    end

    def user_check
      if current_user.id == @my_thread.user_id
        return true
      else
        redirect_to my_threads_path and return
      end
    end

end

5final/board_without_scaffold/app/helpers/application_helper.rb
module ApplicationHelper
end

5final/board_without_scaffold/app/helpers/comments_helper.rb
module CommentsHelper
end

5final/board_without_scaffold/app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

5final/board_without_scaffold/app/views/comments/_form.html.erb
<%= form_with(model: model) do |form| %>
  <p>
    <%= form.text_field :body %>
  </p>

  <div>
    <%= form.submit %>
  </div>
<% end %>

5final/board_without_scaffold/app/views/comments/edit.html.erb
<h3>コメント編集</h3>

<%= render 'form', model: [@my_thread, @comment]%>

<p>
  <%= link_to 'Back', @my_thread %>
</p>

5final/board_without_scaffold/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardPlus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <p>
          <%= p "ログイン中のユーザ: #{current_user.email}さん" %>
        </p>
      <% end %>
    </header>

    <!-- flash[:notice], flash[:alert]を表示する -->
    <p class="notice" id="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <% if user_signed_in? %>
    <p>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
    </p>
    <% end %>

  </body>
</html>

5final/board_without_scaffold/app/views/my_threads/_form.html.erb
<%= form_with(model: my_thread) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

5final/board_without_scaffold/app/views/my_threads/edit.html.erb
<h3>スレッド編集</h3>

<%= render 'form', my_thread: @my_thread%>

<%= link_to '戻る', my_threads_path %>

5final/board_without_scaffold/app/views/my_threads/index.html.erb
<h1>掲示板</h1>

<table>
  <thead>
    <tr>
      <th>記事一覧</th>
    </tr>
  </thead>

  <tbody>
    <% @my_threads.each do |my_thread| %>
      <tr>
        <td><%= link_to my_thread.title, my_thread %></td>
        <% if current_user.id == my_thread.user_id  %>
          <td><%= link_to '[Edit]', edit_my_thread_path(my_thread) %></td>
          <td><%= link_to '[x]',
            my_thread,
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規スレッド作成', new_my_thread_path %>

5final/board_without_scaffold/app/views/my_threads/new.html.erb
<h3>新規スレッド作成</h3>

<%= render 'form', my_thread: @my_thread%>
<%= link_to '戻る', my_threads_path %>

5final/board_without_scaffold/app/views/my_threads/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @my_thread.title %>
</p>



<h4>Comments</h4>

<% if @my_thread.comments.any? %>
  <table>
    <tbody>
      <% @my_thread.comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <% if current_user.id == comment.user_id  %>
        <td><%= link_to '[Edit]', edit_my_thread_comment_path(@my_thread, comment) %></td>
        <td><%= link_to '[x]', my_thread_comment_path(@my_thread, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<%= render 'comments/form', model: [@my_thread, @my_thread.comments.build] %>



<p>
  <%= link_to '戻る', my_threads_path %>
</p>